#!/usr/bin/env python3
"""
Generate .codex/agents/*.toml from .claude/agents/*.md + .agent-personas/*.md.

Source of truth for persona content: .agent-personas/<name>.md
Source of truth for frontmatter (description, effort): .claude/agents/<name>.md
Output: .codex/agents/<name>.toml

Run at session start via setup.sh, or manually after editing personas.
Also run automatically by .claude/git-hooks/pre-commit before every commit.

Note: @file references in persona content (e.g., @memory/..., @cross-stack-...)
appear as literal text in Codex TOML — Codex does not expand them. This is a
known limitation: Claude Code sub-agents get full @file expansion; Codex agents
get the AGENTS.md workspace context loaded natively but not the per-agent files.
"""

import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WORKSPACE = os.path.dirname(SCRIPT_DIR)

CLAUDE_AGENTS_DIR = os.path.join(WORKSPACE, ".claude", "agents")
PERSONAS_DIR = os.path.join(WORKSPACE, ".agent-personas")
CODEX_AGENTS_DIR = os.path.join(WORKSPACE, ".codex", "agents")

EFFORT_MAP = {
    "max": "xhigh",   # Codex does not accept "max" — map to xhigh
    "xhigh": "xhigh",
    "high": "high",
    "medium": "medium",
    "low": "low",
}


def parse_frontmatter(content):
    match = re.match(r"^---\n(.*?)\n---\n", content, re.DOTALL)
    if not match:
        return {}
    fm = {}
    for line in match.group(1).split("\n"):
        if ":" in line:
            key, _, value = line.partition(":")
            fm[key.strip()] = value.strip()
    return fm


def escape_toml_basic_string(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if not os.path.isdir(CLAUDE_AGENTS_DIR):
        print(f"ERROR: {CLAUDE_AGENTS_DIR} not found", file=sys.stderr)
        sys.exit(1)
    if not os.path.isdir(PERSONAS_DIR):
        print(f"ERROR: {PERSONAS_DIR} not found", file=sys.stderr)
        sys.exit(1)

    os.makedirs(CODEX_AGENTS_DIR, exist_ok=True)

    generated = 0
    for filename in sorted(os.listdir(CLAUDE_AGENTS_DIR)):
        if not filename.endswith(".md") or filename == "README.md":
            continue

        name = filename[:-3]
        claude_path = os.path.join(CLAUDE_AGENTS_DIR, filename)
        persona_path = os.path.join(PERSONAS_DIR, filename)
        toml_path = os.path.join(CODEX_AGENTS_DIR, f"{name}.toml")

        with open(claude_path, encoding="utf-8") as f:
            claude_content = f.read()
        fm = parse_frontmatter(claude_content)

        description = escape_toml_basic_string(fm.get("description", ""))
        effort = EFFORT_MAP.get(fm.get("effort", "xhigh"), "xhigh")

        if not os.path.exists(persona_path):
            print(f"ERROR: persona missing for {name}: {persona_path}", file=sys.stderr)
            sys.exit(1)

        with open(persona_path, encoding="utf-8") as f:
            developer_instructions = f.read().strip()

        toml_content = (
            f"# GENERATED — do not edit. Source: .agent-personas/{name}.md + .claude/agents/{name}.md\n"
            f"# Regenerated by setup.sh each session and by .claude/git-hooks/pre-commit on commit.\n"
            f'name = "{name}"\n'
            f'description = "{description}"\n'
            f'model_reasoning_effort = "{effort}"\n'
            f'developer_instructions = """\n'
            + developer_instructions
            + '\n"""\n'
        )

        with open(toml_path, "w", encoding="utf-8") as f:
            f.write(toml_content)

        print(f"  {name}.toml")
        generated += 1

    print(f"Generated {generated} Codex agent TOML files in {CODEX_AGENTS_DIR}")


if __name__ == "__main__":
    main()
